id = "velte"
name = "Velte"
description = "Lightweight Velte syntax highlighting for Zed"
version = "0.2.11"
schema_version = 1
authors = ["Zed Industries <support@iqon.tech>"]
repository = "https://github.com/icotd/zed-velte"

[grammars.velte]
repository = "https://github.com/icotd/tree-sitter-velte.git"
commit = "01e83cf764cc0063551be64d6b1235766c6fe2cd"
